#!/bin/bash

## package managers
echo "==================================================="
echo "========== Cleaning pacman and yay cache... ======="
echo "==================================================="
echo "Cleaning pacman and yay cache..."
sudo pacman -Scc --noconfirm
if command -v yay >/dev/null 2>&1; then
  yay -Scc --noconfirm
else
  echo "yay not found, skipping yay cache clean."
fi
sudo rm -rf /var/cache/pacman/pkg/**

## logs
echo "==================================================="
echo "========= Cleaning logs(journalctl) ==============="
echo "==================================================="
sudo journalctl --vacuum-time=1d
sudo journalctl --vacuum-size=1M

## npm, go
echo "==================================================="
echo "======== Cleaning go modcache.. ==================="
echo "==================================================="
go clean -modcache
echo "Deleting cache folder for go-build.."
rm -rf ~/.cache/go-build/
echo "==================================================="
echo "========== Cleaning npm and nvm cache.. ==========="
echo "==================================================="
npm cache clear --force
echo "Cleaning _npx/ folder"
rm -rf ~/.npm/_npx/*

# rust,cargo
echo "==================================================="
echo "============ Clean cargo registry.. ==============="
echo "==================================================="
rm -rf ~/.cargo/registry/*
echo "==================================================="
echo "=== Cleaning docker containers,images,volumes.. ==="
echo "==================================================="
docker system prune -af
docker image prune -af
docker system prune -af --volumes
docker system df
