#!/usr/bin/env bash

status="$(xset -q | grep Caps | awk '{ print $4 }')"
lockstatus="󰬈"
color="#cad3f5"

if [ "$status" == "off" ]; then
  bgcolor="#24273a"
else
  bgcolor="#b7bdf8"
fi

echo ${lockstatus}
echo ${color}
echo ${bgcolor}
