#!/usr/bin/env bash

status="$(xset -q | grep Caps | awk '{ print $4 }')"
lockstatus="󰬈"
bgcolor="#1e203080"
color="#a6da95"
if [ "$status" == "off" ]; then
  color="#cad3f5"
  lockstatus="󰯫"
fi

echo ${lockstatus} # full text
echo ""            # short text
echo ${color}      # color
echo ${bgcolor}    # bgcolor
