#!/usr/bin/env bash

status="$(xset -q | grep Num | awk '{ print $8 }')"
lockstatus="󰎤"
# bgcolor="#1e203080"
bgcolor="#24273a"
color="#a6da95"
if [ "$status" == "off" ]; then
  color="#cad3f5"
  lockstatus="󰎦"
fi

echo ${lockstatus} # full text
echo ""            # short text
echo ${color}      # color
echo ${bgcolor}    # bgcolor
